backend:
  name: github
  repo: jchrabie/celine
  branch: main

media_folder: "src/assets/img/blog"
public_folder: "/assets/img/blog"

locale: "fr"

collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:

      - label: "Titre"
        name: "title"
        widget: "string"

      - label: "Résumé"
        name: "description"
        widget: "text"

      - label: "Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        format: "DD/MM/YYYY"

      - label: "Contenu"
        name: "body"
        widget: "markdown"