export { DeroulementComponent } from './deroulement/deroulement.component'
export { InstagramFeedComponent } from './instagram-feed/instagram-feed.component'
export { LinkComponent } from './link/link.component'
export { MiniCardComponent } from './mini-card/mini-card.component'
export { TemoignageComponent } from './temoignage/temoignage.component'
